import { phaseOneMockJobs } from "@rolevana/job-sources";
import { publicRuntimeConfig } from "@rolevana/config";
import { Badge, Button, Card } from "@rolevana/ui";
import { ArrowUpRight, Bot, Briefcase, Check, Clock3, Coins, Database, FileText, HardDrive, Radar, ShieldCheck, TriangleAlert } from "lucide-react";
import Link from "next/link";

const metrics = [
  { label: "Jobs discovered", value: "43", delta: "+12 today", icon: Radar },
  { label: "Qualified", value: "18", delta: "42% match", icon: ShieldCheck },
  { label: "Applications", value: "0", delta: "Dry run", icon: Check },
  { label: "Needs review", value: "3", delta: "Human input", icon: TriangleAlert }
];
const statuses = ["QUALIFIED", "READY TO APPLY", "SKIPPED · REGION"];

export default function Dashboard() {
  const config = publicRuntimeConfig(process.env);
  const costMetrics = [
    { label: "AI spend", value: `$${config.maxAiCostUsd.toFixed(2)}`, copy: "Verified-free models only", icon: Coins },
    { label: "AI requests", value: "0", copy: `Batches of up to ${config.aiJobAnalysisBatchSize}`, icon: Bot },
    { label: "Database tier", value: "Free", copy: "Supabase-compatible", icon: Database },
    { label: "Resume storage", value: "0 MB", copy: `${config.tailoredResumeRetentionDays}-day PDF retention`, icon: HardDrive }
  ];
  return <div className="space-y-7">
    <section className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><Badge className="mb-4 border-cyan-300/20 bg-cyan-300/10 text-cyan-200">Phase 1 · Foundation</Badge><h1 className="m-0 max-w-3xl text-3xl font-semibold tracking-[-.04em] md:text-5xl">Your job search,<br/><span className="text-slate-500">quietly in motion.</span></h1><p className="mt-4 max-w-xl text-sm leading-6 text-slate-400">Complete your source-of-truth profile and master resume. Rolevana will only automate from facts you provide.</p></div><Button asChild size="lg"><Link href="/profile">Complete profile <ArrowUpRight size={17}/></Link></Button></section>
    <Card className="overflow-hidden"><div className="grid gap-px bg-white/[.06] md:grid-cols-[1.4fr_1fr_1fr]"><div className="bg-slate-900 p-6"><div className="mb-5 flex items-center justify-between"><span className="text-xs font-bold uppercase tracking-[.14em] text-slate-500">Autopilot</span><Badge className="border-slate-600 text-slate-400">Off</Badge></div><div className="flex items-end gap-3"><span className="text-4xl font-semibold tracking-tight">0</span><span className="pb-1 text-slate-500">/ 100 today</span></div><div className="mt-4 h-1.5 overflow-hidden rounded-full bg-white/[.06]"><div className="h-full w-0 bg-cyan-400"/></div></div><div className="bg-slate-900 p-6"><div className="text-xs font-bold uppercase tracking-[.14em] text-slate-500">Next job hunt</div><div className="mt-6 flex items-center gap-3 text-2xl font-semibold"><Clock3 className="text-cyan-300"/>Not scheduled</div><p className="text-xs text-slate-500">Enable after profile setup</p></div><div className="bg-slate-900 p-6"><div className="text-xs font-bold uppercase tracking-[.14em] text-slate-500">Safety mode</div><div className="mt-6 flex items-center gap-3 text-2xl font-semibold"><ShieldCheck className="text-emerald-300"/>Dry run</div><p className="text-xs text-slate-500">Real submissions are blocked</p></div></div></Card>
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{metrics.map(({label,value,delta,icon:Icon}) => <Card className="p-5" key={label}><div className="mb-5 flex items-center justify-between"><span className="text-sm text-slate-400">{label}</span><Icon size={17} className="text-slate-600"/></div><div className="text-3xl font-semibold tracking-tight">{value}</div><div className="mt-1 text-xs text-slate-500">{delta}</div></Card>)}</section>
    <section><div className="mb-3 flex items-center justify-between"><h2 className="m-0 text-base font-semibold">Cost & usage</h2><div className="flex gap-2"><Badge className="border-emerald-300/20 bg-emerald-300/10 text-emerald-200">AI · Free only</Badge><Badge className="border-emerald-300/20 bg-emerald-300/10 text-emerald-200">Infrastructure · Free</Badge></div></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{costMetrics.map(({label,value,copy,icon:Icon}) => <Card className="p-5" key={label}><div className="flex items-center justify-between text-sm text-slate-400"><span>{label}</span><Icon size={16}/></div><div className="mt-4 text-2xl font-semibold">{value}</div><div className="mt-1 text-xs text-slate-500">{copy}</div></Card>)}</div><p className="mb-0 mt-2 text-[11px] text-slate-600">Free-tier labels reflect configuration, not independently verified provider billing statements.</p></section>
    <section className="grid gap-5 xl:grid-cols-[1.7fr_1fr]"><Card><div className="flex items-center justify-between border-b border-white/[.07] p-5"><div><h2 className="m-0 text-base font-semibold">Fresh remote roles</h2><p className="mb-0 mt-1 text-xs text-slate-500">Mock source · newest first</p></div><Button asChild variant="ghost" size="sm"><Link href="/jobs">View all <ArrowUpRight size={14}/></Link></Button></div><div>{phaseOneMockJobs.map((job,index) => <div className="grid gap-3 border-b border-white/[.05] px-5 py-4 last:border-0 md:grid-cols-[1fr_auto_auto] md:items-center" key={job.externalJobId}><div><div className="font-medium">{job.title}</div><div className="mt-1 text-xs text-slate-500">{job.companyName} · {job.remoteRegions.join(", ")}</div></div><Badge className={index === 2 ? "text-amber-200" : "text-cyan-200"}>{index === 0 ? "91% match" : index === 1 ? "86% match" : "Location check"}</Badge><span className="text-xs text-slate-500">{statuses[index]}</span></div>)}</div></Card><Card className="p-5"><div className="flex items-center gap-2"><FileText size={18} className="text-cyan-300"/><h2 className="m-0 text-base font-semibold">Setup checklist</h2></div><div className="mt-5 space-y-4">{[["Candidate profile","Add verified facts",false],["Master resume","Upload PDF or DOCX",false],["Remote regions","Confirm eligibility",false],["Dry-run pipeline","Ready",true]].map(([title,copy,done]) => <div className="flex items-start gap-3" key={String(title)}><span className={`mt-0.5 grid size-5 place-items-center rounded-full border ${done ? "border-emerald-400/30 bg-emerald-400/10 text-emerald-300" : "border-white/10 text-slate-600"}`}>{done ? <Check size={12}/> : null}</span><div><div className="text-sm font-medium">{title}</div><div className="mt-1 text-xs text-slate-500">{copy}</div></div></div>)}</div><Button asChild variant="secondary" className="mt-6 w-full"><Link href="/profile"><Briefcase size={15}/>Set up Rolevana</Link></Button></Card></section>
  </div>;
}
