import Link from "next/link";
import { Badge, Button, Card } from "@rolevana/ui";
import { getSessionUser } from "@/lib/auth";
import { listApplicationPackages } from "@/lib/application-service";

const label = (value: string) => value.replaceAll("_", " ");
export default async function ApplicationsPage() {
  const user = await getSessionUser(); const packages = user ? await listApplicationPackages(user.id) : [];
  return <div><div className="flex items-end justify-between gap-4"><div><h1 className="m-0 text-3xl font-semibold">Applications</h1><p className="mt-2 text-sm text-slate-400">Prepared review packages only. Nothing shown here has been submitted.</p></div><Badge>{packages.length} prepared</Badge></div>{packages.length ? <div className="mt-6 grid gap-4">{packages.map((pkg) => <Card className="p-5" key={pkg.id}><div className="flex flex-wrap items-center justify-between gap-4"><div><div className="text-lg font-semibold">{pkg.jobSnapshot.title}</div><div className="text-sm text-slate-400">{pkg.jobSnapshot.company} · package {pkg.id} · v{pkg.packageVersion}</div><div className="mt-3 flex flex-wrap gap-2"><Badge>Match {pkg.match.score}%</Badge><Badge>{label(pkg.resume.strategy)}</Badge><Badge>ATS {pkg.resume.atsCompatibilityAfter.compatibilityScore}</Badge><Badge>{label(pkg.resume.truthfulnessStatus)}</Badge><Badge>{label(pkg.applicationMethod.type)} · {pkg.applicationMethod.provider??"Unknown"}</Badge><Badge>{label(pkg.authorization.verificationStatus)}</Badge><Badge>{label(pkg.reviewStatus)}</Badge><Badge>{label(pkg.readinessStatus)}</Badge></div></div><div className="text-right"><Button asChild><Link href={`/applications/${pkg.id}/review`}>Review package</Link></Button><div className="mt-2 text-xs font-medium text-amber-300">Not submitted</div></div></div></Card>)}</div> : <Card className="mt-6 grid min-h-72 place-items-center p-8 text-center"><div><div className="text-lg font-semibold">No prepared packages yet</div><p className="mx-auto max-w-md text-sm leading-6 text-slate-500">Open a qualified job and choose Prepare application package. Rolevana will stop before submission.</p><Button asChild className="mt-3" variant="secondary"><Link href="/jobs">Browse qualified jobs</Link></Button></div></Card>}</div>;
}
