"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { Button } from "@rolevana/ui";
import type { ApplicationAnswer, ResumeSelectionStrategy } from "@rolevana/applications";

async function updatePackage(id: string, body: Record<string, unknown>) { const response = await fetch(`/api/applications/${id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify(body) }); const payload = await response.json() as { error?: string }; if (!response.ok) throw new Error(payload.error ?? "Update failed"); }
export function ApplicationReviewActions({ packageId, canApprove, jobId }: { packageId: string; canApprove: boolean; jobId: string }) {
  const router = useRouter(); const [busy, setBusy] = useState(""); const [note, setNote] = useState(""); const [error, setError] = useState("");
  const act = async (action: string, extra: Record<string, unknown> = {}) => { setBusy(action); setError(""); try { await updatePackage(packageId, { action, ...extra }); router.refresh(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Update failed"); } finally { setBusy(""); } };
  return <div className="space-y-3"><div className="flex flex-wrap gap-2"><Button disabled={!canApprove || Boolean(busy)} onClick={() => act("APPROVE")}>{busy === "APPROVE" ? "Approving…" : "Approve package"}</Button><Button disabled={Boolean(busy)} variant="secondary" onClick={() => act("REBUILD")}>{busy === "REBUILD" ? "Rebuilding…" : "Rebuild package"}</Button><Button variant="secondary" onClick={() => router.push(`/jobs/${jobId}`)}>Return to job</Button></div><div className="flex max-w-2xl gap-2"><input className="min-w-0 flex-1 rounded-lg border border-white/10 bg-black/20 px-3 py-2 text-sm" placeholder="Optional change note" value={note} onChange={(event) => setNote(event.target.value)}/><Button disabled={Boolean(busy)} variant="secondary" onClick={() => act("NEEDS_CHANGES", { note })}>Needs changes</Button></div>{!canApprove && <p className="m-0 text-xs text-amber-300">Resolve every blocking item before approval.</p>}{error && <p className="m-0 text-xs text-rose-400">{error}</p>}</div>;
}
export function AnswerEditor({ packageId, answer, locked = false }: { packageId: string; answer: ApplicationAnswer; locked?: boolean }) {
  const router = useRouter(); const [value, setValue] = useState(answer.currentAnswer ?? answer.answer ?? ""); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const count = answer.characterLimit ? `${value.length} / ${answer.characterLimit} characters` : answer.wordLimit ? `${value.trim() ? value.trim().split(/\s+/).length : 0} / ${answer.wordLimit} words` : null;
  return <div><textarea className="mt-2 min-h-24 w-full rounded-lg border border-white/10 bg-black/20 p-3 text-sm text-slate-200" disabled={locked} maxLength={answer.characterLimit} value={value} onChange={(event) => setValue(event.target.value)}/><div className="mt-2 flex items-center justify-between gap-3"><span className="text-[11px] text-slate-500">{locked ? "Rebuild this stale package before editing" : count ?? `${answer.source.replaceAll("_", " ")} · confidence ${Math.round(answer.confidence * 100)}%`}</span><Button size="sm" variant="secondary" disabled={locked || busy || value === (answer.currentAnswer ?? answer.answer ?? "")} onClick={async () => { setBusy(true); setError(""); try { await updatePackage(packageId, { action: "EDIT_ANSWER", answerId: answer.id, value }); router.refresh(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Save failed"); } finally { setBusy(false); } }}>{busy ? "Saving…" : "Save answer"}</Button></div>{error && <p className="text-xs text-rose-400">{error}</p>}</div>;
}
export function ResumeSelector({ packageId, strategy, tailoredAvailable, locked = false }: { packageId: string; strategy: ResumeSelectionStrategy; tailoredAvailable: boolean; locked?: boolean }) {
  const router = useRouter(); const [busy, setBusy] = useState(false); const choose = async (next: ResumeSelectionStrategy) => { setBusy(true); try { await updatePackage(packageId, { action: "SELECT_RESUME", strategy: next }); router.refresh(); } finally { setBusy(false); } };
  return <div className="flex flex-wrap gap-2"><Button size="sm" variant={strategy === "MASTER_RESUME" ? "primary" : "secondary"} disabled={locked || busy} onClick={() => choose("MASTER_RESUME")}>Use master resume</Button>{tailoredAvailable && <Button size="sm" variant={strategy === "TAILORED_RESUME" ? "primary" : "secondary"} disabled={locked || busy} onClick={() => choose("TAILORED_RESUME")}>Use tailored resume</Button>}</div>;
}
