"use client";
import { useState } from "react";
import type { BrainRecord } from "@rolevana/brain";
import type { PreparedApplicationPackage } from "@rolevana/applications";
import { Button, Card } from "@rolevana/ui";
import { TailoredResumePreview } from "./tailored-resume-preview";

const actions={WHY_MATCH:"Why is this job a match?",WHY_REJECTED:"Why was this job rejected?",WHY_TAILORED:"Why was this resume tailored?",SHOW_CHANGES:"Show exact changes",EXPLAIN_BULLET:"Explain this bullet",SHOW_EVIDENCE:"Show evidence for this statement",MATCHING_SKILLS:"Show matching skills",MISSING_SKILLS:"Show missing JD requirements",COMPARE_JD_RESUME:"Compare JD with resume",TAILORED_RESUME_PREVIEW:"Generate tailored resume preview",USE_MASTER_RESUME:"Use master resume instead",EXPLAIN_ATS:"Explain ATS compatibility",WHY_REVIEW:"Why does this need review?"} as const;
type Action=keyof typeof actions;

export function RolevanaAssistant({record,applicationPackage}:{record:BrainRecord;applicationPackage:PreparedApplicationPackage|null|undefined}){
  const[action,setAction]=useState<Action>("WHY_MATCH");const[output,setOutput]=useState("");
  function run(){const match=record.match;const firstChange=record.resumeVersion?.changes?.[0];const values:Record<Action,string>={WHY_MATCH:match?`Internal compatibility ${match.overallScore}/100. ${match.evidence.map((item)=>item.reason).join(" ")}`:"No match result exists yet.",WHY_REJECTED:record.transitions.at(-1)?.reason??"Not rejected.",WHY_TAILORED:applicationPackage?.resume.strategy==="MASTER_RESUME"?"Tailoring was not required; the prepared package selected the master resume.":record.resumeVersion?.changes?.map((item)=>item.why).join(" ")||"The master resume was selected without tailoring.",SHOW_CHANGES:record.resumeVersion?.changes?.map((item)=>`${item.type}: ${item.before} → ${item.after}`).join("\n\n")||"No tailored changes exist.",EXPLAIN_BULLET:firstChange?`${firstChange.after}\nReason: ${firstChange.why}`:"No rewritten bullet exists.",SHOW_EVIDENCE:firstChange?`Evidence IDs: ${firstChange.evidenceIds.join(", ")}`:"No tailored statement is selected.",MATCHING_SKILLS:match?.matchedSkills.join(", ")||"No verified matching skills identified.",MISSING_SKILLS:match?.missingRequiredSkills.join(", ")||"No missing required skills identified.",COMPARE_JD_RESUME:applicationPackage?`Selected ${applicationPackage.resume.strategy.replaceAll("_"," ")}. ATS compatibility ${applicationPackage.resume.atsCompatibilityAfter.compatibilityScore}/100.`:match?`${match.matchedSkills.length} matched; ${match.missingRequiredSkills.length} missing. ATS compatibility ${record.resumeVersion?.baselineATS?.atsCompatibilityScore??"—"} → ${record.ats?.atsCompatibilityScore??"—"}.`:"Process this job first.",TAILORED_RESUME_PREVIEW:record.resumeVersion?.content.bullets.map((item)=>`• ${item.text} [${item.sourceEvidenceIds.join(", ")}]`).join("\n")||"No tailored preview is available.",USE_MASTER_RESUME:applicationPackage?.resume.strategy==="MASTER_RESUME"||record.resumeStrategy==="MASTER_RESUME"?"The master resume is already selected.":"This remains a preview action; the stored master resume is never changed.",EXPLAIN_ATS:applicationPackage?`ATS compatibility ${applicationPackage.resume.atsCompatibilityAfter.compatibilityScore}/100 (internal).`:record.ats?`ATS compatibility ${record.ats.atsCompatibilityScore}/100 (internal). ${record.ats.issues.join(" ")||"No critical compatibility issue identified."}`:"ATS validation has not run.",WHY_REVIEW:applicationPackage?.blockers.map((item)=>item.message).join(" ")||record.reviewReasons.join(" ")||"This item does not currently require review."};setOutput(values[action]);}
  return <div className="space-y-5"><Card className="p-5"><h2 className="mt-0 text-base">Rolevana Assistant</h2><p className="text-xs text-slate-500">Constrained to this job and its persisted intelligence.</p><select className="w-full rounded-md border border-white/10 bg-slate-950 p-2 text-sm" value={action} onChange={(event)=>setAction(event.target.value as Action)}>{Object.entries(actions).map(([id,label])=><option value={id} key={id}>{label}</option>)}</select><Button className="mt-3" variant="secondary" onClick={run}>Run action</Button>{output&&<div className="mt-4 whitespace-pre-wrap rounded-md bg-white/[.04] p-3 text-xs leading-5 text-slate-300">{output}</div>}</Card><TailoredResumePreview record={record} applicationPackage={applicationPackage}/></div>;
}
