"use client";
import { useEffect, useState, type FormEvent } from "react";
import { Badge, Button, Card } from "@rolevana/ui";
import { jobSourceDisplayName, type JobSourceRegistryRecord } from "@rolevana/job-sources";
import { DiscoveryControls } from "./discovery-controls";
import { PageSkeleton } from "./page-skeleton";

export function SourceManager() {
  const [sources, setSources] = useState<JobSourceRegistryRecord[]>([]);
  const [loaded, setLoaded] = useState(false);
  const [companyName, setCompanyName] = useState(""); const [boardUrl, setBoardUrl] = useState(""); const [message, setMessage] = useState("");
  const load = () => fetch("/api/job-sources").then((response) => response.json()).then((body: { sources?: JobSourceRegistryRecord[] }) => setSources(body.sources ?? [])).finally(() => setLoaded(true));
  useEffect(() => { void load(); }, []);
  async function add(event: FormEvent) { event.preventDefault(); const response = await fetch("/api/job-sources", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ companyName, boardUrl }) }); const body = await response.json() as { error?: string }; setMessage(response.ok ? "Source added." : body.error ?? "Could not add source."); if (response.ok) { setBoardUrl(""); setCompanyName(""); await load(); } }
  async function toggle(source: JobSourceRegistryRecord) { await fetch("/api/job-sources", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ id: source.id, enabled: !source.enabled }) }); await load(); }
  if (!loaded) return <PageSkeleton/>;
  const publicSources=sources.filter((source)=>source.sourceType!=="DIRECT_ATS"&&source.sourceType!=="PORTAL");const atsSources=sources.filter((source)=>source.sourceType==="DIRECT_ATS");const portals=sources.filter((source)=>source.sourceType==="PORTAL");
  const table=(items:JobSourceRegistryRecord[])=><Card className="mt-4 overflow-x-auto"><div className="min-w-[1050px]"><div className="grid grid-cols-[1.2fr_.8fr_.7fr_.8fr_1fr_1fr_.7fr_.6fr_.6fr] border-b border-white/[.06] px-5 py-3 text-[10px] font-bold uppercase tracking-[.12em] text-slate-600"><span>Name</span><span>Type</span><span>Enabled</span><span>Health</span><span>Last sync</span><span>Next eligible</span><span>Interval</span><span>Fetched</span><span>Latency</span></div>{items.map((source)=><div className="grid grid-cols-[1.2fr_.8fr_.7fr_.8fr_1fr_1fr_.7fr_.6fr_.6fr] items-center border-b border-white/[.06] px-5 py-4 text-xs last:border-0" key={source.id}><span className="font-medium">{source.companyName}<span className="block text-[10px] text-slate-600">{jobSourceDisplayName(source.provider)}</span></span><span>{source.sourceType==="PORTAL"?"Portal":source.sourceType??"Unknown"}</span>{source.sourceType==="PORTAL"?<span className="text-slate-500">Not active</span>:<button className="w-fit text-cyan-200" onClick={()=>toggle(source)}>{source.enabled?"Enabled":"Disabled"}</button>}<Badge className="w-fit">{source.sourceType==="PORTAL"?"Not connected":source.health??(source.lastError?"FAILED":"NOT CONFIGURED")}</Badge><span className="text-slate-500">{source.lastSyncAt?new Date(source.lastSyncAt).toLocaleString():"Never"}</span><span className="text-slate-500">{source.nextSyncAt?new Date(source.nextSyncAt).toLocaleString():"Due"}</span><span>{source.minimumPollIntervalMinutes??60}m</span><span>{source.recordsFetched??source.jobCount}</span><span>{source.lastLatencyMs??0} ms</span></div>)}</div></Card>;
  return <div><div className="flex flex-wrap items-end justify-between gap-4"><div><h1 className="m-0 text-3xl font-semibold">Sources</h1><p className="mt-2 text-sm text-slate-400">Observable, zero-cost public discovery. Each adapter controls its own safe polling interval.</p></div><DiscoveryControls/></div><h2 className="mb-0 mt-7 text-base">Public APIs & RSS</h2>{table(publicSources)}<h2 className="mb-0 mt-7 text-base">Company ATS boards <Badge>{atsSources.length}</Badge></h2>{table(atsSources)}<h2 className="mb-0 mt-7 text-base">Future portal connectors</h2><p className="mt-2 text-xs text-slate-500">Portal discovery is not enabled yet. Rolevana does not use undocumented scraping or bypass portal protections.</p>{table(portals)}<Card className="mt-6 p-5"><h2 className="m-0 text-base font-semibold">Add public ATS board</h2><p className="mt-1 text-xs text-slate-500">Supports public Ashby, Greenhouse, Lever, SmartRecruiters, and Workable board URLs.</p><form className="mt-4 grid gap-3 md:grid-cols-[.8fr_1.5fr_auto]" onSubmit={add}><input className="control" value={companyName} onChange={(event)=>setCompanyName(event.target.value)} placeholder="Company name"/><input className="control" required value={boardUrl} onChange={(event)=>setBoardUrl(event.target.value)} placeholder="https://jobs.ashbyhq.com/company"/><Button type="submit">Add source</Button></form>{message&&<p className="mb-0 text-xs text-slate-400">{message}</p>}</Card></div>;
}
