"use client";
import { useEffect, useState, type FormEvent } from "react";
import { Badge, Button, Card } from "@rolevana/ui";
import type { JobSourceRegistryRecord } from "@rolevana/job-sources";
import { DiscoveryControls } from "./discovery-controls";
import { PageSkeleton } from "./page-skeleton";

export function SourceManager() {
  const [sources, setSources] = useState<JobSourceRegistryRecord[]>([]);
  const [loaded, setLoaded] = useState(false);
  const [companyName, setCompanyName] = useState(""); const [boardUrl, setBoardUrl] = useState(""); const [message, setMessage] = useState("");
  const load = () => fetch("/api/job-sources").then((response) => response.json()).then((body: { sources?: JobSourceRegistryRecord[] }) => setSources(body.sources ?? [])).finally(() => setLoaded(true));
  useEffect(() => { void load(); }, []);
  async function add(event: FormEvent) { event.preventDefault(); const response = await fetch("/api/job-sources", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ companyName, boardUrl }) }); const body = await response.json() as { error?: string }; setMessage(response.ok ? "Source added." : body.error ?? "Could not add source."); if (response.ok) { setBoardUrl(""); setCompanyName(""); await load(); } }
  async function toggle(source: JobSourceRegistryRecord) { await fetch("/api/job-sources", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ id: source.id, enabled: !source.enabled }) }); await load(); }
  if (!loaded) return <PageSkeleton/>;
  return <div><div className="flex flex-wrap items-end justify-between gap-4"><div><h1 className="m-0 text-3xl font-semibold">Sources</h1><p className="mt-2 text-sm text-slate-400">Observable discovery coverage. Rolevana scans only the enabled public feeds and boards below.</p></div><DiscoveryControls/></div><Card className="mt-6 overflow-hidden"><div className="hidden grid-cols-[1.1fr_.8fr_.7fr_.8fr_.6fr_.6fr] border-b border-white/[.06] px-5 py-3 text-[10px] font-bold uppercase tracking-[.14em] text-slate-600 md:grid"><span>Company</span><span>Provider</span><span>Enabled</span><span>Last scan</span><span>Jobs</span><span>Health</span></div>{sources.map((source) => <div className="grid gap-2 border-b border-white/[.06] px-5 py-4 last:border-0 md:grid-cols-[1.1fr_.8fr_.7fr_.8fr_.6fr_.6fr] md:items-center" key={source.id}><span className="font-medium">{source.companyName}</span><span className="text-xs text-slate-400">{source.provider}</span><button className="w-fit text-left text-xs text-cyan-200" onClick={() => toggle(source)}>{source.enabled ? "Enabled" : "Disabled"}</button><span className="text-xs text-slate-500">{source.lastSuccessfulScan ? new Date(source.lastSuccessfulScan).toLocaleString() : "Never"}</span><span>{source.jobCount}</span><Badge className="w-fit">{source.lastError ? "Failing" : source.lastSuccessfulScan ? "Healthy" : "Not scanned"}</Badge></div>)}</Card><Card className="mt-6 p-5"><h2 className="m-0 text-base font-semibold">Add public ATS board</h2><p className="mt-1 text-xs text-slate-500">Paste an Ashby, Greenhouse, or Lever board URL; Rolevana derives the identifier.</p><form className="mt-4 grid gap-3 md:grid-cols-[.8fr_1.5fr_auto]" onSubmit={add}><input className="control" value={companyName} onChange={(event) => setCompanyName(event.target.value)} placeholder="Company name"/><input className="control" required value={boardUrl} onChange={(event) => setBoardUrl(event.target.value)} placeholder="https://jobs.ashbyhq.com/company"/><Button type="submit">Add source</Button></form>{message && <p className="mb-0 text-xs text-slate-400">{message}</p>}</Card></div>;
}
