import { getSessionUser } from "@/lib/auth";
import { readLocalJobById } from "@/lib/job-store";
import { Badge, Button, Card } from "@rolevana/ui";
import { ExternalLink } from "lucide-react";
import { notFound } from "next/navigation";
import { humanJobStatus } from "@/lib/job-list-filter";

export default async function JobDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const user = await getSessionUser(); const { id } = await params; const job = user ? await readLocalJobById(user.id, id) : null; if (!job) notFound();
  const values = [["Company",job.companyName],["Source",job.source],["Workplace",job.workplaceType],["Remote regions",job.remoteRegions.join(", ")],["Locations",job.locations.join(", ") || "Unknown"],["Employment",job.employmentType ?? "Unknown"],["Department / team",[job.department,job.team].filter(Boolean).join(" / ") || "Unknown"],["Salary",job.salaryMin !== undefined ? `${job.salaryCurrency ?? ""} ${job.salaryMin}${job.salaryMax !== undefined ? `–${job.salaryMax}` : ""} ${job.salaryInterval ?? ""}` : "Not listed"],["Posted",job.postedAt?.toLocaleString() ?? "Unknown"],["Discovered",job.discoveredAt.toLocaleString()],["Last seen",job.lastSeenAt.toLocaleString()],["Classification",job.frontendClassification],["Decision reason",job.classificationReason],["Dedupe fingerprint",job.dedupeFingerprint],["Source references",String(job.sourceReferences.length)]];
  return <div><div className="flex flex-wrap items-start justify-between gap-4"><div><Badge>{humanJobStatus(job.status)}</Badge><h1 className="mb-1 mt-4 text-3xl font-semibold">{job.title}</h1><p className="m-0 text-slate-400">{job.companyName}</p></div><Button asChild><a href={job.jobUrl} target="_blank" rel="noreferrer">Open original job <ExternalLink size={15}/></a></Button></div><div className="mt-6 grid gap-5 xl:grid-cols-[1.4fr_.8fr]"><Card className="p-6"><h2 className="mt-0 text-lg">Job description</h2><div className="whitespace-pre-wrap text-sm leading-7 text-slate-300">{job.description}</div></Card><div className="space-y-5"><Card className="overflow-hidden">{values.map(([label,value]) => <div className="border-b border-white/[.06] p-4 last:border-0" key={label}><div className="text-[10px] font-bold uppercase tracking-[.12em] text-slate-600">{label}</div><div className="mt-1 break-words text-sm">{value}</div></div>)}</Card><Card className="p-5"><div className="text-sm font-semibold">Application safety</div><p className="mb-0 text-xs leading-5 text-slate-500">Phase 2 does not submit applications. The application URL is retained only as public source data.</p></Card></div></div></div>;
}
