import { describe, expect, it } from "vitest";
import { RolevanaOrchestrator, buildAssistantContext, buildEvidenceGraph, calculatePriority, createTailoredResume, matchJob, qualifyJob, runWorkerPool, sanitizeCandidateProfile, validateATS, validateTruthfulness } from "./index";
import type { CandidateProfile, MasterResume } from "@rolevana/domain";
import type { NormalizedJob } from "@rolevana/job-sources";

const profile = { fullName:"Sufiyan Ahmed",preferredName:"Sufiyan",email:"s@example.com",phone:"+91 9999999999",city:"Delhi",country:"India",timezone:"Asia/Kolkata",linkedInUrl:"https://linkedin.com/in/private",githubUrl:"https://github.com/private",portfolioUrl:"",websiteUrl:"",currentEmployer:"Argument Driven Inquiry",currentRole:"Frontend Engineer",totalYearsExperience:3,noticePeriod:"30 days",currentCompensation:"",expectedCompensation:"",preferredSalaryRange:"",currency:"INR",employmentTypes:["FULL_TIME"],remoteOnly:true,allowedRegions:["India","Worldwide","APAC"],workAuthorization:"",sponsorshipRequired:"UNKNOWN",relocationWillingness:"CASE_BY_CASE",timezoneFlexibility:"",primaryTargetRoleTitle:"Frontend Engineer",primaryTargetRoleCategory:"FRONTEND_ENGINEERING",targetRoleSelectionSource:"RESUME",secondaryTargetRoles:[],includeRelatedTitles:true,experienceToleranceYears:1,minimumSeniority:"UNKNOWN",maximumSeniority:"UNKNOWN",skills:["React","TypeScript","Next.js","Redux","GraphQL","REST","Cypress","Tailwind","Node.js","AWS"].map((name)=>({name})),experience:[{company:"Argument Driven Inquiry",role:"Frontend Engineer",location:"",startDate:"2023",current:true,summary:"Sufiyan built React UI",achievements:["Improved tested flows"],technologies:["React","TypeScript","GraphQL","Cypress"]}],projects:[{name:"Warehouse CRM",description:"Next.js inventory UI",technologies:["Next.js","Redux","Tailwind"],achievements:[],links:[]}],education:[] } satisfies CandidateProfile;
const job = (update: Partial<NormalizedJob> = {}): NormalizedJob => ({ id:"job-a",externalJobId:"a",source:"MOCK",companyName:"Company A",title:"Frontend Engineer",description:"Requires 3+ years React TypeScript GraphQL Cypress. Remote Worldwide.",requirements:["React","TypeScript","GraphQL","Cypress"],preferredQualifications:[],workplaceType:"REMOTE",remoteRegions:["REMOTE_WORLDWIDE"],locationRestrictions:[],locations:["Worldwide"],postedAt:new Date("2026-09-28T23:30:00Z"),discoveredAt:new Date("2026-09-28T23:30:00Z"),lastSeenAt:new Date("2026-09-28T23:30:00Z"),jobUrl:"https://example.com/job",applicationUrl:"https://example.com/apply",canonicalUrl:"https://example.com/job",sourceMetadata:{},descriptionHash:"hash-a",dedupeFingerprint:"fp-a",status:"QUALIFIED_BY_FILTER",frontendClassification:"FRONTEND",roleCategory:"FRONTEND",seniority:"MID",minimumYearsExperience:3,classificationReason:"fixture",freshness:"JUST_POSTED",sourceReferences:[],...update });
const resume = { id:"00000000-0000-4000-8000-000000000001",originalFileName:"resume.pdf",mimeType:"application/pdf",sizeBytes:100,storageKey:"resume.pdf",checksum:"a".repeat(64),uploadedAt:new Date(),rawText:"Verified React TypeScript experience",parsedData:{personal:{},links:{},career:{},skills:[],experience:[],projects:[],education:[],warnings:[]},parsingStatus:"VERIFIED",verificationStatus:"VERIFIED" } satisfies MasterResume;

describe("Rolevana Brain", () => {
  it("sanitizes PII without mutating the profile", () => { const value = JSON.stringify(sanitizeCandidateProfile(profile)); expect(value).not.toMatch(/Sufiyan|s@example|9999999999|linkedin|github|Argument Driven Inquiry/); expect(profile.fullName).toBe("Sufiyan Ahmed"); });
  it("deterministically qualifies role, experience and location before AI", () => expect(qualifyJob(job(), profile)).toMatchObject({ qualified:true,state:"QUALIFIED" }));
  it("rejects backend/experience mismatch", () => expect(qualifyJob(job({title:"Senior Backend Java Engineer",roleCategory:"BACKEND",minimumYearsExperience:8}), profile).state).toBe("REJECTED_ROLE"));
  it("finds verified skill evidence and never invents Kubernetes", () => { const result=matchJob(job({requirements:["React","TypeScript","Kubernetes"],description:"React TypeScript Kubernetes required"}),profile); expect(result.missingRequiredSkills).toContain("Kubernetes"); const content=createTailoredResume(profile,result,buildEvidenceGraph(profile)); expect(content.orderedSkills).not.toContain("Kubernetes"); });
  it("orders fresher jobs ahead when match is equal", () => { const match=matchJob(job(),profile); const fresh=calculatePriority(job(),match,new Date("2026-09-29T00:00:00Z")); const old=calculatePriority(job({postedAt:new Date("2026-09-20")}),match,new Date("2026-09-29T00:00:00Z")); expect(fresh.score).toBeGreaterThan(old.score); });
  it("validates ATS compatibility and rejects unsupported claims", () => { const graph=buildEvidenceGraph(profile); const match=matchJob(job(),profile,graph); const content=createTailoredResume(profile,match,graph); expect(validateATS(job(),content,match).layoutSafe).toBe(true); expect(validateTruthfulness({...content,bullets:[...content.bullets,{id:"fake",text:"Led 100 engineers",sourceEvidenceIds:[]}]},graph).valid).toBe(false); });
  it("runs the full dry-run state machine without submission or email", () => { const record=new RolevanaOrchestrator({minimumMatchScore:75}).process(job(),profile,resume,1); expect(["APPLICATION_PREPARED","NEEDS_REVIEW"]).toContain(record.state); expect(record.applicationsSubmitted).toBe(0); expect(record.emailsSent).toBe(0); expect(record.truthfulness?.valid).toBe(true); });
  it("uses five workers and priority order", async () => { const active=new Set<number>(); let max=0; const order:string[]=[]; const values=Array.from({length:10},(_,i)=>({id:String(i),priorityScore:10-i})); await runWorkerPool(values,5,async(item,worker)=>{ active.add(worker); max=Math.max(max,active.size); order.push(item.id); await new Promise((resolve)=>setTimeout(resolve,2)); active.delete(worker); }); expect(max).toBe(5); expect(order.slice(0,5)).toEqual(["0","1","2","3","4"]); });
  it("minimizes limited-assistant context", () => { const record=new RolevanaOrchestrator().process(job(),profile,resume); const context=buildAssistantContext("WHY_MATCH",record,job()); expect(context).not.toHaveProperty("candidateProfile"); expect(JSON.stringify(context)).not.toContain(profile.email); });
});
