import { afterEach, describe, expect, it, vi } from "vitest";
import { mkdtemp, mkdir, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { tmpdir } from "node:os";
import { createEmptyCandidateProfile, type CandidateProfile } from "@rolevana/domain";
import type { NormalizedJob } from "@rolevana/job-sources";
import { determineApplicationMethod, prepareApplicationPackage, prepareCustomTextAnswer, prepareDeterministicAnswers, resolveJobJurisdiction } from "./application-service";
import { readReviewQueue, syncApplicationPackageReview } from "./brain-store";

const originalDataDirectory = process.env.ROLEVANA_LOCAL_DATA_DIR;
afterEach(() => { if (originalDataDirectory === undefined) delete process.env.ROLEVANA_LOCAL_DATA_DIR; else process.env.ROLEVANA_LOCAL_DATA_DIR = originalDataDirectory; vi.restoreAllMocks(); });
const job = (overrides: Partial<NormalizedJob> = {}): NormalizedJob => ({ id: "job-1", externalJobId: "external-1", source: "REMOTE_OK", sourceType: "PUBLIC_API", companyName: "Bjak", title: "Frontend Engineer", description: "React and TypeScript", requirements: ["React"], preferredQualifications: [], workplaceType: "REMOTE", remoteRegions: ["REMOTE_APAC"], locationRestrictions: [], locations: ["Singapore"], discoveredAt: new Date("2026-09-30T00:00:00Z"), lastSeenAt: new Date("2026-09-30T00:00:00Z"), jobUrl: "https://remoteok.com/job", applicationUrl: "https://remoteok.com/job", canonicalUrl: "https://remoteok.com/job", sourceMetadata: {}, descriptionHash: "hash", dedupeFingerprint: "dedupe", status: "QUALIFIED_BY_FILTER", frontendClassification: "FRONTEND", roleCategory: "FRONTEND_ENGINEERING", seniority: "MID", classificationReason: "Target match", freshness: "TODAY", lifecycleStatus: "ACTIVE", atsProvider: "UNKNOWN", sourceReferences: [], ...overrides });
const profile = (): CandidateProfile => ({ ...createEmptyCandidateProfile(), fullName: "Test Candidate", email: "test@example.test", phone: "0000000000", city: "Pune", country: "India", currentRole: "Frontend Engineer", currentEmployer: "Example Co", totalYearsExperience: 3, noticePeriod: "30 days", primaryTargetRoleTitle: "Frontend Engineer", primaryTargetRoleCategory: "FRONTEND_ENGINEERING", skills: [{ name: "React", years: 3 }], workAuthorizations: [{ jurisdiction: "Singapore", status: "AUTHORIZED", requiresSponsorship: "NO", verified: true, verifiedAt: "2026-09-30T00:00:00.000Z" }] });

describe("Phase 4 application preparation service", () => {
  it("classifies a Remote OK-only URL as an aggregator listing", () => expect(determineApplicationMethod(job())).toMatchObject({ type: "AGGREGATOR_LISTING", provider: "Remote OK", urlClassification: "AGGREGATOR_LISTING", confidence: .95, executionSupport: "NOT_IMPLEMENTED" }));
  it("classifies a direct Greenhouse URL independently of discovery source", () => { const candidate = job({ source: "REMOTE_OK", applicationUrl: "https://boards.greenhouse.io/bjak/jobs/123", atsProvider: "UNKNOWN" }); expect(candidate.source).toBe("REMOTE_OK"); expect(determineApplicationMethod(candidate)).toMatchObject({ type: "DIRECT_ATS", provider: "GREENHOUSE", urlClassification: "EMPLOYER_DESTINATION" }); });
  it("classifies a direct Lever URL independently of discovery source", () => expect(determineApplicationMethod(job({ source: "JOBICY", applicationUrl: "https://jobs.lever.co/bjak/abc", atsProvider: "UNKNOWN" }))).toMatchObject({ type: "DIRECT_ATS", provider: "LEVER" }));
  it("classifies email only when the listing explicitly provides one", () => expect(determineApplicationMethod(job({ applicationEmail: "jobs@example.test" }))).toMatchObject({ type: "EMAIL_APPLICATION", url: "mailto:jobs@example.test" }));
  it("leaves an unsupported application path unknown", () => expect(determineApplicationMethod(job({ source: "MOCK", applicationUrl: "", canonicalUrl: "", jobUrl: "" }))).toMatchObject({ type: "UNKNOWN", urlClassification: "UNKNOWN", confidence: 0, executionSupport: "NOT_IMPLEMENTED" }));
  it("does not turn APAC or Worldwide into an authorization jurisdiction", () => { expect(resolveJobJurisdiction(job({ locations: [], remoteRegions: ["REMOTE_APAC"] }))).toBeNull(); expect(resolveJobJurisdiction(job({ locations: [], remoteRegions: ["REMOTE_WORLDWIDE"] }))).toBeNull(); });
  it("resolves an explicitly named country", () => expect(resolveJobJurisdiction(job({ locations: ["Singapore"], remoteRegions: ["REMOTE_APAC"] }))).toBe("Singapore"));
  it("prepares deterministic evidence-backed answers without AI", () => { const answers = prepareDeterministicAnswers(profile(), "Singapore"); expect(answers.find((item) => item.id === "years-experience")).toMatchObject({ answer: "3", source: "PROFILE_VERIFIED" }); expect(answers.find((item) => item.id === "work-authorization")).toMatchObject({ answer: "AUTHORIZED", source: "JURISDICTION_AUTHORIZATION" }); });
  it("does not invent authorization questions when only a region is known", () => { const answers = prepareDeterministicAnswers(profile(), null); expect(answers.some((item) => item.normalizedQuestionType === "WORK_AUTHORIZATION" || item.normalizedQuestionType === "SPONSORSHIP")).toBe(false); });
  it("maps a verified notice period deterministically", () => expect(prepareDeterministicAnswers(profile(), "Singapore").find((item) => item.id === "notice-period")).toMatchObject({ answer: "30 days", source: "PROFILE_VERIFIED", reviewRequired: false }));
  it("keeps a missing notice period unresolved", () => { const missing = { ...profile(), noticePeriod: "" }; expect(prepareDeterministicAnswers(missing, "Singapore").find((item) => item.id === "notice-period")).toMatchObject({ answer: null, source: "NEEDS_USER_INPUT", reviewRequired: true }); });
  it("never guesses jurisdiction-specific authorization", () => { const answers = prepareDeterministicAnswers(profile(), "US"); expect(answers.find((item) => item.id === "work-authorization")).toMatchObject({ answer: null, source: "NEEDS_USER_INPUT", reviewRequired: true }); });
  it("drafts constrained custom text only from supplied verified evidence", () => { const drafted = prepareCustomTextAnswer({ id: "react", question: "Describe your React experience", verifiedStatements: ["Built verified React interfaces.", "Improved a verified dashboard."], evidenceIds: ["experience-1"], wordLimit: 5 }); expect(drafted).toMatchObject({ source: "MASTER_RESUME_VERIFIED", evidenceIds: ["experience-1"], reviewRequired: false }); expect(drafted.answer?.split(/\s+/)).toHaveLength(5); const empty = prepareCustomTextAnswer({ id: "why", question: "Why us?", verifiedStatements: [], evidenceIds: [] }); expect(empty.source).toBe("NEEDS_USER_INPUT"); });
  it("deduplicates Review Queue items by package and resolves the same item", async () => { const root = await mkdtemp(path.join(tmpdir(), "rolevana-review-")); process.env.ROLEVANA_LOCAL_DATA_DIR = root; try { const input = { packageId: "package-1", jobId: "job-1", jobTitle: "Frontend Engineer", company: "Bjak", reasons: ["Review"], category: "PACKAGE_REVIEW" as const, open: true }; const first = await syncApplicationPackageReview("user", input); const second = await syncApplicationPackageReview("user", { ...input, reasons: ["Updated"] }); await syncApplicationPackageReview("user", { ...input, open: false }); const items = await readReviewQueue("user"); expect(second.id).toBe(first.id); expect(items).toHaveLength(1); expect(items[0]?.state).toBe("RESOLVED"); } finally { await rm(root, { recursive: true, force: true }); } });
  it("refuses to prepare Lemon.io while it needs classification and performs no external request", async () => { const root = await mkdtemp(path.join(tmpdir(), "rolevana-lemon-")); process.env.ROLEVANA_LOCAL_DATA_DIR = root; process.env.DRY_RUN = "true"; process.env.FREE_AI_ONLY = "true"; process.env.FREE_INFRA_MODE = "true"; process.env.MAX_AI_COST_USD = "0"; const fetchSpy = vi.spyOn(globalThis, "fetch"); try { const userDir = path.join(root, "user"); await mkdir(path.join(userDir, "job-details"), { recursive: true }); await writeFile(path.join(userDir, "profile.json"), JSON.stringify(profile())); await writeFile(path.join(userDir, "job-details", "lemon.json"), JSON.stringify({ ...job({ id: "lemon", companyName: "Lemon.io", title: "Senior Java & React Developer", status: "NEEDS_CLASSIFICATION" }), discoveredAt: "2026-09-30T00:00:00.000Z", lastSeenAt: "2026-09-30T00:00:00.000Z" })); await expect(prepareApplicationPackage("user", "lemon")).rejects.toThrow("JOB_NOT_QUALIFIED"); expect(fetchSpy).not.toHaveBeenCalled(); } finally { await rm(root, { recursive: true, force: true }); } });
});
