import { createHash } from "node:crypto";
import { approveApplicationPackage, createPreparedApplicationPackage, editApplicationAnswer, extractApplicationInstructions, markPackageStale, overrideResumeSelection, rebuildApplicationPackage, requestApplicationChanges, type ApplicationAnswer, type ApplicationMethod, type ATSCompatibilitySnapshot, type DependencyHashes, type PreparedApplicationPackage, type ResumeSelectionStrategy } from "@rolevana/applications";
import { buildEvidenceGraph, createMasterResumeRepresentation, diffResumeContent, hasMeasurableATSGain, RolevanaOrchestrator, validateATS, type ATSCompatibility, type BrainRecord } from "@rolevana/brain";
import type { CandidateProfile, MasterResume } from "@rolevana/domain";
import { detectATS, jobSourceDisplayName, type NormalizedJob } from "@rolevana/job-sources";
import { readApplicationPackage, readApplicationPackageForJob, readApplicationPackages, saveApplicationPackage } from "./application-store";
import { readBrainRecord, saveBrainRecord, syncApplicationPackageReview } from "./brain-store";
import { readLocalJobById } from "./job-store";
import { readLocalProfile, readLocalResume } from "./local-store";

const jsonHash = (value: unknown) => createHash("sha256").update(JSON.stringify(value)).digest("hex");
const normalize = (value: string) => value.toLowerCase().replace(/[^a-z0-9]/g, "");
const assertPhase4Safety = () => { if (process.env.DRY_RUN !== "true") throw new Error("PHASE_4_REQUIRES_DRY_RUN"); if (process.env.FREE_AI_ONLY !== "true" || Number(process.env.MAX_AI_COST_USD) !== 0 || process.env.FREE_INFRA_MODE !== "true") throw new Error("PHASE_4_ZERO_COST_SAFETY_ASSERTION_FAILED"); };

const countryAliases: Array<[string, string[]]> = [
  ["India", ["india"]], ["United States", ["united states", "usa", "u.s."]], ["United Kingdom", ["united kingdom", "uk", "u.k."]], ["United Arab Emirates", ["united arab emirates", "uae", "u.a.e."]], ["Singapore", ["singapore"]], ["Australia", ["australia"]], ["Canada", ["canada"]], ["New Zealand", ["new zealand"]], ["Germany", ["germany"]], ["France", ["france"]], ["Netherlands", ["netherlands"]], ["Ireland", ["ireland"]], ["Spain", ["spain"]], ["Portugal", ["portugal"]], ["Japan", ["japan"]], ["Malaysia", ["malaysia"]], ["Philippines", ["philippines"]], ["Indonesia", ["indonesia"]], ["Thailand", ["thailand"]], ["Vietnam", ["vietnam"]], ["Israel", ["israel"]], ["Saudi Arabia", ["saudi arabia"]], ["Qatar", ["qatar"]], ["Bahrain", ["bahrain"]],
];
export function resolveJobJurisdiction(job: NormalizedJob) { const text = job.locations.join(" | ").toLowerCase(); const countries = countryAliases.filter(([, aliases]) => aliases.some((alias) => new RegExp(`(^|[^a-z])${alias.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}([^a-z]|$)`, "i").test(text))).map(([country]) => country); return countries.length === 1 ? countries[0]! : null; }

export function determineApplicationMethod(job: NormalizedJob): ApplicationMethod {
  if (job.applicationEmail) return { type: "EMAIL_APPLICATION", provider: null, url: `mailto:${job.applicationEmail}`, urlClassification: "EMAIL_INSTRUCTION", confidence: 1, sourceConfidence: 1, executionSupport: "NOT_IMPLEMENTED" };
  const url = /^https?:\/\//i.test(job.applicationUrl) ? job.applicationUrl : null;
  const detected = url ? detectATS(url) : { provider: "UNKNOWN" as const };
  if (["GREENHOUSE", "LEVER", "ASHBY", "SMARTRECRUITERS", "WORKABLE"].includes(detected.provider)) return { type: "DIRECT_ATS", provider: detected.provider, url, urlClassification: "EMPLOYER_DESTINATION", confidence: 1, sourceConfidence: 1, executionSupport: "NOT_IMPLEMENTED" };
  if (["GREENHOUSE", "LEVER", "ASHBY", "SMARTRECRUITERS", "WORKABLE"].includes(job.atsProvider ?? "") && url) return { type: "DIRECT_ATS", provider: job.atsProvider!, url, urlClassification: "EMPLOYER_DESTINATION", confidence: .9, sourceConfidence: 1, executionSupport: "NOT_IMPLEMENTED" };
  const hostname = url ? new URL(url).hostname.toLowerCase().replace(/^www\./, "") : "";
  const aggregators: Record<string, string> = { "remoteok.com": "Remote OK", "jobicy.com": "Jobicy", "weworkremotely.com": "We Work Remotely", "remotive.com": "Remotive" };
  const aggregator = Object.entries(aggregators).find(([domain]) => hostname === domain || hostname.endsWith(`.${domain}`));
  if (aggregator) return { type: "AGGREGATOR_LISTING", provider: aggregator[1], url, urlClassification: "AGGREGATOR_LISTING", confidence: .95, sourceConfidence: 1, executionSupport: "NOT_IMPLEMENTED" };
  if (["LINKEDIN", "INDEED", "NAUKRI", "WELLFOUND", "ARC"].includes(job.source)) return { type: "PORTAL", provider: jobSourceDisplayName(job.source), url, urlClassification: "PORTAL_LISTING", confidence: url ? .9 : .3, sourceConfidence: 1, executionSupport: "NOT_IMPLEMENTED" };
  if (job.source === "COMPANY_CAREER_PAGE" || (url && job.companyDomain && hostname.endsWith(job.companyDomain.toLowerCase()))) return { type: "COMPANY_CAREER_PAGE", provider: job.companyName, url, urlClassification: "EMPLOYER_DESTINATION", confidence: .9, sourceConfidence: 1, executionSupport: "NOT_IMPLEMENTED" };
  return { type: "UNKNOWN", provider: null, url, urlClassification: "UNKNOWN", confidence: 0, sourceConfidence: 1, executionSupport: "NOT_IMPLEMENTED" };
}

const atsSnapshot = (value: ATSCompatibility): ATSCompatibilitySnapshot => ({ compatibilityScore: value.atsCompatibilityScore, keywordCoverage: value.keywordCoverage, requiredSkillCoverage: value.requiredSkillCoverage, layoutSafe: value.layoutSafe, missingVerifiedRequirements: value.issues.filter((item) => /missing verified/i.test(item)), warnings: [...value.issues, ...value.suggestions] });
const regionLabels: Record<string, string> = { REMOTE_WORLDWIDE: "Worldwide", REMOTE_INDIA: "India", REMOTE_APAC: "APAC", REMOTE_US_ONLY: "United States", REMOTE_CANADA_ONLY: "Canada", REMOTE_EU_ONLY: "Europe", REMOTE_UK_ONLY: "United Kingdom", REMOTE_LATAM: "LATAM", UNKNOWN: "Unknown" };
const answer = (id: string, question: string, normalizedQuestionType: ApplicationAnswer["normalizedQuestionType"], value: string | null, source: ApplicationAnswer["source"], options: Partial<ApplicationAnswer> = {}): ApplicationAnswer => ({ id, question, normalizedQuestionType, answer: value, currentAnswer: value ?? "", source, evidenceIds: [], confidence: source === "NEEDS_USER_INPUT" ? 0 : 1, reviewRequired: source === "NEEDS_USER_INPUT", sensitive: false, jurisdiction: null, editedByUser: false, ...options });

export function prepareDeterministicAnswers(profile: CandidateProfile, jurisdiction: string | null): ApplicationAnswer[] {
  const authorization = jurisdiction ? profile.workAuthorizations.find((item) => normalize(item.jurisdiction) === normalize(jurisdiction) && item.verified) : undefined;
  const answers = [
    answer("years-experience", "How many years of professional experience do you have?", "YEARS_EXPERIENCE", String(profile.totalYearsExperience), "PROFILE_VERIFIED", { evidenceIds: ["profile-total-years-experience"] }),
    answer("current-role", "What is your current role?", "CURRENT_ROLE", profile.currentRole || null, profile.currentRole ? "PROFILE_VERIFIED" : "NEEDS_USER_INPUT", { evidenceIds: profile.currentRole ? ["profile-current-role"] : [] }),
    answer("current-employer", "Who is your current employer?", "CURRENT_EMPLOYER", profile.currentEmployer || null, profile.currentEmployer ? "PROFILE_VERIFIED" : "NEEDS_USER_INPUT", { sensitive: true, evidenceIds: profile.currentEmployer ? ["profile-current-employer"] : [] }),
    answer("location", "What is your current location?", "LOCATION", [profile.city, profile.country].filter(Boolean).join(", ") || null, profile.city && profile.country ? "PROFILE_VERIFIED" : "NEEDS_USER_INPUT", { sensitive: true, evidenceIds: ["profile-location"] }),
    answer("notice-period", "What is your notice period?", "NOTICE_PERIOD", profile.noticePeriod || null, profile.noticePeriod ? "PROFILE_VERIFIED" : "NEEDS_USER_INPUT", { evidenceIds: profile.noticePeriod ? ["profile-notice-period"] : [] }),
    answer("remote-preference", "Are you seeking remote work?", "REMOTE_PREFERENCE", profile.remoteOnly ? "Yes — remote only" : "Flexible", "PROFILE_VERIFIED", { evidenceIds: ["profile-remote-preference"] }),
    answer("relocation", "Are you willing to relocate?", "RELOCATION", profile.relocationWillingness.replaceAll("_", " "), "PROFILE_VERIFIED", { evidenceIds: ["profile-relocation"] }),
    answer("skills", "What relevant skills do you have?", "SKILLS", profile.skills.map((item) => item.name).join(", "), "PROFILE_VERIFIED", { evidenceIds: profile.skills.map((_, index) => `skill-${index}`) }),
  ];
  if (jurisdiction) answers.push(answer("work-authorization", `Are you authorized to work in ${jurisdiction}?`, "WORK_AUTHORIZATION", authorization && authorization.status !== "UNKNOWN" ? authorization.status : null, authorization && authorization.status !== "UNKNOWN" ? "JURISDICTION_AUTHORIZATION" : "NEEDS_USER_INPUT", { jurisdiction, sensitive: true, evidenceIds: authorization ? [`authorization-${normalize(jurisdiction)}`] : [] }), answer("sponsorship", `Will you require sponsorship in ${jurisdiction}?`, "SPONSORSHIP", authorization && authorization.requiresSponsorship !== "UNKNOWN" ? authorization.requiresSponsorship : null, authorization && authorization.requiresSponsorship !== "UNKNOWN" ? "JURISDICTION_AUTHORIZATION" : "NEEDS_USER_INPUT", { jurisdiction, sensitive: true, evidenceIds: authorization ? [`authorization-${normalize(jurisdiction)}`] : [] }));
  if (profile.expectedCompensation) answers.push(answer("expected-compensation", `What is your expected compensation (${profile.currency})?`, "EXPECTED_COMPENSATION", profile.expectedCompensation, "PROFILE_VERIFIED", { sensitive: true, reviewRequired: true, evidenceIds: ["profile-expected-compensation"] }));
  if (profile.portfolioUrl) answers.push(answer("portfolio", "Portfolio URL", "PORTFOLIO", profile.portfolioUrl, "PROFILE_VERIFIED", { sensitive: true, evidenceIds: ["profile-portfolio"] }));
  if (profile.linkedInUrl) answers.push(answer("linkedin", "LinkedIn URL", "LINKEDIN", profile.linkedInUrl, "PROFILE_VERIFIED", { sensitive: true, evidenceIds: ["profile-linkedin"] }));
  if (profile.githubUrl) answers.push(answer("github", "GitHub URL", "GITHUB", profile.githubUrl, "PROFILE_VERIFIED", { sensitive: true, evidenceIds: ["profile-github"] }));
  return answers;
}

export function prepareCustomTextAnswer(input: { id: string; question: string; verifiedStatements: string[]; evidenceIds: string[]; characterLimit?: number; wordLimit?: number }): ApplicationAnswer {
  let value = input.verifiedStatements.filter(Boolean).join(" ");
  if (input.wordLimit && value) value = value.split(/\s+/).slice(0, input.wordLimit).join(" ");
  if (input.characterLimit && value.length > input.characterLimit) value = value.slice(0, input.characterLimit).trimEnd();
  return answer(input.id, input.question, "CUSTOM_TEXT", value || null, value && input.evidenceIds.length ? "MASTER_RESUME_VERIFIED" : "NEEDS_USER_INPUT", { evidenceIds: value ? input.evidenceIds : [], confidence: value && input.evidenceIds.length ? 1 : 0, reviewRequired: !value || !input.evidenceIds.length, ...(input.characterLimit === undefined ? {} : { characterLimit: input.characterLimit }), ...(input.wordLimit === undefined ? {} : { wordLimit: input.wordLimit }) });
}

export function dependencyHashes(job: NormalizedJob, profile: CandidateProfile, resume: MasterResume | null, selectedResume: string): DependencyHashes {
  return { job: jsonHash({ descriptionHash: job.descriptionHash, lifecycleStatus: job.lifecycleStatus ?? "ACTIVE", applicationUrl: job.applicationUrl, atsProvider: job.atsProvider }), profile: jsonHash(profile), masterResume: resume ? jsonHash({ id: resume.id, checksum: resume.checksum, verificationStatus: resume.verificationStatus, verifiedVersionHash: resume.verifiedVersionHash }) : "missing", selectedResume, authorization: jsonHash(profile.workAuthorizations), targetRole: jsonHash({ title: profile.primaryTargetRoleTitle, category: profile.primaryTargetRoleCategory, source: profile.targetRoleSelectionSource }) };
}

function buildPackage(job: NormalizedJob, profile: CandidateProfile, resume: MasterResume | null, brain: BrainRecord): PreparedApplicationPackage {
  if (!brain.match || !brain.ats || !brain.truthfulness) throw new Error("BRAIN_INTELLIGENCE_INCOMPLETE");
  const graph = buildEvidenceGraph(profile, resume); const masterContent = createMasterResumeRepresentation(profile, graph); const masterATS = validateATS(job, masterContent, brain.match);
  const tailored = brain.resumeVersion?.strategy === "TAILORED_RESUME" && brain.resumeVersion.validationStatus === "VERIFIED" && hasMeasurableATSGain(masterATS, brain.resumeVersion.atsCompatibility) ? brain.resumeVersion : null;
  const strategy: ResumeSelectionStrategy = tailored ? "TAILORED_RESUME" : "MASTER_RESUME"; const selectedVersion = tailored?.id ?? resume?.id ?? "missing-master-resume";
  const authorizationJurisdiction = resolveJobJurisdiction(job); const authorizationRecord = authorizationJurisdiction ? profile.workAuthorizations.find((item) => normalize(item.jurisdiction) === normalize(authorizationJurisdiction) && item.verified) : undefined;
  const changes = tailored ? (tailored.changes?.length ? tailored.changes : diffResumeContent(masterContent, tailored.content)).map((item) => ({ id: item.id, before: item.before, after: item.after, reason: item.why, evidenceIds: item.evidenceIds, atsImpact: `${tailored.atsCompatibility.atsCompatibilityScore - masterATS.atsCompatibilityScore >= 0 ? "+" : ""}${tailored.atsCompatibility.atsCompatibilityScore - masterATS.atsCompatibilityScore} compatibility points` })) : [];
  const evidenceCount = tailored?.content.bullets.length ?? masterContent.bullets.length; const supportedCount = (tailored?.content.bullets ?? masterContent.bullets).filter((item) => item.sourceEvidenceIds.length).length;
  const prepared = createPreparedApplicationPackage({ id: `application-${jsonHash(job.id ?? job.descriptionHash).slice(0, 16)}`, jobId: job.id ?? job.descriptionHash, jobSnapshot: { title: job.title, company: job.companyName, location: job.locations.join(", ") || job.remoteRegions.join(", "), source: jobSourceDisplayName(job.source), canonicalJobUrl: job.canonicalUrl, applicationUrl: job.applicationUrl || null, atsProvider: job.atsProvider ?? null, descriptionHash: job.descriptionHash, lifecycleStatus: job.lifecycleStatus ?? "ACTIVE" }, candidateProfileVersion: jsonHash(profile), targetRole: profile.primaryTargetRoleTitle, jobRegionEligibility: { regions: job.remoteRegions.map((region) => regionLabels[region] ?? region), status: job.status === "QUALIFIED_BY_FILTER" ? "REGION_ELIGIBLE" : "UNKNOWN" }, match: { score: brain.match.overallScore, matchedSkills: brain.match.matchedSkills, missingSkills: brain.match.missingRequiredSkills, strengths: brain.match.evidence.filter((item) => item.score >= 70).map((item) => item.reason), concerns: [...brain.match.missingRequiredSkills.map((item) => `Missing verified requirement: ${item}`), ...brain.reviewReasons.filter((item) => !/master resume verification|authorization|sponsorship/i.test(item))] }, resume: { strategy, masterResumeVersion: resume?.id ?? "", masterResumeVerified: resume?.verificationStatus === "VERIFIED", selectedResumeVersion: selectedVersion, ...(tailored ? { tailoredResumeVersion: tailored.id } : {}), atsCompatibilityBefore: atsSnapshot(masterATS), atsCompatibilityAfter: atsSnapshot(tailored?.atsCompatibility ?? masterATS), truthfulnessStatus: brain.truthfulness.status, evidenceCoverage: evidenceCount ? Math.round(supportedCount / evidenceCount * 100) : 100, unsupportedClaims: [...brain.truthfulness.rejectedBulletIds, ...brain.truthfulness.unsupportedSkills], warnings: brain.ats.issues, changes, manualOverride: false }, answers: prepareDeterministicAnswers(profile, authorizationJurisdiction), authorization: { jurisdiction: authorizationJurisdiction, jurisdictionResolution: authorizationJurisdiction ? "COUNTRY_SPECIFIC" : "AUTHORIZATION_JURISDICTION_UNKNOWN", workAuthorizationStatus: authorizationRecord?.status ?? "UNKNOWN", sponsorshipStatus: authorizationRecord?.requiresSponsorship ?? "UNKNOWN", verificationStatus: authorizationRecord?.verified ? "VERIFIED" : "UNVERIFIED" }, applicationMethod: determineApplicationMethod(job), applicationInstructions: extractApplicationInstructions(job.description, `job-description:${job.descriptionHash}`), blockers: [], warnings: ["Prepared locally in dry-run mode. No application has been submitted.", ...(strategy === "MASTER_RESUME" && brain.resumeStrategy === "TAILORED_RESUME" ? ["Tailored version was not selected because it did not provide a measurable ATS compatibility improvement."] : [])], reviewNotes: [], dependencies: dependencyHashes(job, profile, resume, selectedVersion) });
  return prepared;
}

const reviewCategory = (pkg: PreparedApplicationPackage) => pkg.reviewStatus === "STALE" ? "STALE_PACKAGE" as const : pkg.blockers.some((item) => item.code === "MASTER_RESUME_UNVERIFIED" || item.code === "UNSUPPORTED_RESUME_CLAIM") ? "RESUME_VERIFICATION" as const : pkg.blockers.some((item) => item.code === "AUTHORIZATION_JURISDICTION_UNKNOWN" || item.code === "WORK_AUTHORIZATION_UNKNOWN") ? "AUTHORIZATION" as const : pkg.blockers.some((item) => item.code === "SPONSORSHIP_UNKNOWN") ? "SPONSORSHIP" as const : pkg.blockers.some((item) => item.code === "LEGAL_ATTESTATION") ? "LEGAL_QUESTION" as const : pkg.blockers.some((item) => item.answerId) ? "APPLICATION_ANSWER" as const : "PACKAGE_REVIEW" as const;
async function persist(userId: string, pkg: PreparedApplicationPackage) { await saveApplicationPackage(userId, pkg); await syncApplicationPackageReview(userId, { packageId: pkg.id, jobId: pkg.jobId, jobTitle: pkg.jobSnapshot.title, company: pkg.jobSnapshot.company, reasons: pkg.blockers.length ? pkg.blockers.map((item) => `${item.code}: ${item.message}`) : [pkg.reviewStatus === "APPROVED" ? "Prepared and approved. Not submitted." : "Package is ready for human review."], category: reviewCategory(pkg), open: !["APPROVED", "READY_TO_APPLY"].includes(pkg.readinessStatus) }); return pkg; }

async function loadInputs(userId: string, jobId: string) { const [job, profile, resume, existingBrain] = await Promise.all([readLocalJobById(userId, jobId), readLocalProfile(userId), readLocalResume(userId), readBrainRecord(userId, jobId)]); if (!job || !profile) throw new Error("JOB_OR_PROFILE_NOT_FOUND"); return { job, profile, resume, existingBrain }; }
export async function prepareApplicationPackage(userId: string, jobId: string, rebuild = false) {
  assertPhase4Safety(); const { job, profile, resume, existingBrain } = await loadInputs(userId, jobId); if (job.status !== "QUALIFIED_BY_FILTER") throw new Error("JOB_NOT_QUALIFIED_FOR_APPLICATION_PREPARATION");
  let brain = existingBrain; if (!brain || brain.jobHash !== job.descriptionHash || !brain.match || !brain.ats || !brain.truthfulness) { brain = new RolevanaOrchestrator().process(job, profile, resume); await saveBrainRecord(userId, brain); }
  if (!brain.match || !brain.ats || !brain.truthfulness) throw new Error("BRAIN_INTELLIGENCE_INCOMPLETE"); const fresh = buildPackage(job, profile, resume, brain); const existing = await readApplicationPackageForJob(userId, jobId);
  if (!existing) return persist(userId, fresh); if (JSON.stringify(existing.dependencies) === JSON.stringify(fresh.dependencies) && !rebuild) return existing;
  if (!rebuild) return persist(userId, markPackageStale(existing, fresh.dependencies)); return persist(userId, rebuildApplicationPackage(existing, fresh));
}

export async function getApplicationPackage(userId: string, packageId: string) { const pkg = await readApplicationPackage(userId, packageId); if (!pkg) return null; const { job, profile, resume } = await loadInputs(userId, pkg.jobId); const current = dependencyHashes(job, profile, resume, pkg.resume.selectedResumeVersion); const checked = markPackageStale(pkg, current); return checked === pkg ? pkg : persist(userId, checked); }
export async function listApplicationPackages(userId: string) { const packages = await readApplicationPackages(userId); return Promise.all(packages.map((pkg) => getApplicationPackage(userId, pkg.id).then((value) => value ?? pkg))); }
export async function approvePackage(userId: string, packageId: string) { const pkg = await getApplicationPackage(userId, packageId); if (!pkg) throw new Error("APPLICATION_PACKAGE_NOT_FOUND"); return persist(userId, approveApplicationPackage(pkg)); }
export async function markPackageNeedsChanges(userId: string, packageId: string, note: string) { const pkg = await getApplicationPackage(userId, packageId); if (!pkg) throw new Error("APPLICATION_PACKAGE_NOT_FOUND"); return persist(userId, requestApplicationChanges(pkg, note)); }
export async function updateApplicationAnswer(userId: string, packageId: string, answerId: string, value: string) { const pkg = await getApplicationPackage(userId, packageId); if (!pkg) throw new Error("APPLICATION_PACKAGE_NOT_FOUND"); return persist(userId, editApplicationAnswer(pkg, answerId, value)); }
export async function selectPackageResume(userId: string, packageId: string, strategy: ResumeSelectionStrategy) { const pkg = await getApplicationPackage(userId, packageId); if (!pkg) throw new Error("APPLICATION_PACKAGE_NOT_FOUND"); const selected = strategy === "TAILORED_RESUME" ? pkg.resume.tailoredResumeVersion : pkg.resume.masterResumeVersion; if (!selected) throw new Error("REQUESTED_RESUME_VERSION_NOT_AVAILABLE"); return persist(userId, overrideResumeSelection(pkg, { strategy, selectedResumeVersion: selected, truthfulnessStatus: pkg.resume.truthfulnessStatus })); }
export async function rebuildPackage(userId: string, packageId: string) { const pkg = await readApplicationPackage(userId, packageId); if (!pkg) throw new Error("APPLICATION_PACKAGE_NOT_FOUND"); return prepareApplicationPackage(userId, pkg.jobId, true); }
