import { mkdir, readFile, rename, writeFile } from "node:fs/promises";
import path from "node:path";
import { randomUUID } from "node:crypto";
import type { BrainRecord, ResumeVersion, WorkerActivity } from "@rolevana/brain";
import { getLocalDataDirectory } from "./local-store";

const safe=(value:string)=>value.replace(/[^a-zA-Z0-9_-]/g,"_");
const directory=(userId:string)=>path.join(getLocalDataDirectory(),safe(userId),"brain");
const file=(userId:string,name:string)=>path.join(directory(userId),name);
const read=async<T>(target:string,fallback:T):Promise<T>=>{try{return JSON.parse(await readFile(target,"utf8")) as T;}catch{return fallback;}};
const write=async(target:string,value:unknown)=>{await mkdir(path.dirname(target),{recursive:true});const temporary=`${target}.${process.pid}.${randomUUID()}.tmp`;await writeFile(temporary,JSON.stringify(value,null,2),"utf8");await rename(temporary,target);};

export type ReviewItem={id:string;jobId:string;jobTitle:string;company:string;reasons:string[];state:"OPEN"|"RESOLVED";createdAt:string};
export type BrainMetrics={jobsProcessedToday:number;qualifiedToday:number;matchedToday:number;resumeReadyToday:number;applicationReadyToday:number;ultraCallsToday:number;ultraAverageLatency:number;ultraTasksAvoidedByDeterministicLogic:number;applicationsSubmittedToday:0;emailsSentToday:0};
export type BrainSnapshot={records:BrainRecord[];activities:WorkerActivity[];reviews:ReviewItem[];metrics:BrainMetrics};
export type BrainQueueItem={jobId:string;queuedAt:string;reason:string;status:"QUEUED"|"PROCESSING"|"COMPLETED"|"REMOVED_NOT_QUALIFIED"};
export async function enqueueBrainJobs(userId:string,jobs:Array<{id?:string;descriptionHash:string}>){const current=await read<BrainQueueItem[]>(file(userId,"queue.json"),[]);const known=new Set(current.map((item)=>item.jobId));const now=new Date().toISOString();const additions=jobs.map((job)=>job.id??job.descriptionHash).filter((jobId)=>!known.has(jobId)).map((jobId)=>({jobId,queuedAt:now,reason:"New deterministic target-role, region, and experience qualifier.",status:"QUEUED" as const}));if(additions.length)await write(file(userId,"queue.json"),[...current,...additions].slice(-1000));return additions.length;}
export async function readBrainQueue(userId:string){return read<BrainQueueItem[]>(file(userId,"queue.json"),[]);}
export async function setBrainQueueStatus(userId:string,jobId:string,status:BrainQueueItem["status"]){const current=await readBrainQueue(userId);await write(file(userId,"queue.json"),current.map((item)=>item.jobId===jobId?{...item,status}:item));}
export async function reconcileBrainQueueEligibility(userId:string,jobs:Array<{id?:string;descriptionHash:string;status:string}>){const current=await readBrainQueue(userId);const byId=new Map(jobs.map((job)=>[job.id??job.descriptionHash,job]));let removed=0;const next=current.map((item)=>{const job=byId.get(item.jobId);if((item.status==="QUEUED"||item.status==="PROCESSING")&&job?.status!=="QUALIFIED_BY_FILTER"){removed+=1;return{...item,status:"REMOVED_NOT_QUALIFIED" as const,reason:"Removed because deterministic reclassification no longer considers the job qualified."};}return item;});if(removed)await write(file(userId,"queue.json"),next);return removed;}
export async function readBrainRecords(userId:string){return read<BrainRecord[]>(file(userId,"records.json"),[]);}
export async function readBrainRecord(userId:string,jobId:string){return (await readBrainRecords(userId)).find((item)=>item.jobId===jobId)??null;}
export async function saveBrainRecord(userId:string,record:BrainRecord){const current=await readBrainRecords(userId);const next=[record,...current.filter((item)=>item.jobId!==record.jobId)].slice(0,1000);await write(file(userId,"records.json"),next);if(record.resumeVersion)await write(file(userId,`resume-versions/${safe(record.resumeVersion.id)}.json`),record.resumeVersion);await syncReview(userId,record);await appendLog(userId,record);}
async function syncReview(userId:string,record:BrainRecord){const current=await read<ReviewItem[]>(file(userId,"review-queue.json"),[]);const existing=current.find((item)=>item.jobId===record.jobId&&item.state==="OPEN");if(!record.reviewReasons.length){if(existing)await write(file(userId,"review-queue.json"),current.map((item)=>item.id===existing.id?{...item,state:"RESOLVED" as const}:item));return;}const item:ReviewItem={id:existing?.id??randomUUID(),jobId:record.jobId,jobTitle:record.jobTitle,company:record.company,reasons:record.reviewReasons,state:"OPEN",createdAt:existing?.createdAt??new Date().toISOString()};await write(file(userId,"review-queue.json"),[item,...current.filter((value)=>value.id!==item.id)]);}
async function appendLog(userId:string,record:BrainRecord){const current=await read<Array<Record<string,unknown>>>(file(userId,"events.json"),[]);const events=record.provenance.map((item)=>({jobId:record.jobId,task:item.task,provider:item.provider,model:item.model,durationMs:item.latencyMs,resultStatus:record.state,fallbackCount:item.fallbackCount,estimatedCost:item.aiCostUsd,aiNecessary:item.aiNecessary??false,at:item.timestamp??record.updatedAt}));await write(file(userId,"events.json"),[...events,...current].slice(0,5000));}
export async function saveWorkerActivities(userId:string,activities:WorkerActivity[]){await write(file(userId,"worker-activity.json"),activities);}
export async function readWorkerActivities(userId:string){return read<WorkerActivity[]>(file(userId,"worker-activity.json"),[]);}
export async function readReviewQueue(userId:string){return read<ReviewItem[]>(file(userId,"review-queue.json"),[]);}
export async function readResumeVersion(userId:string,id:string){return read<ResumeVersion|null>(file(userId,`resume-versions/${safe(id)}.json`),null);}
export function brainMetrics(records:BrainRecord[],now=new Date()):BrainMetrics{const day=now.toISOString().slice(0,10);const today=records.filter((record)=>record.startedAt.slice(0,10)===day);const ultra=today.flatMap((record)=>record.provenance).filter((item)=>item.provider==="nvidia"&&item.model.includes("nemotron-3-ultra"));return{jobsProcessedToday:today.length,qualifiedToday:today.filter((item)=>item.transitions.some((value)=>value.state==="QUALIFIED")).length,matchedToday:today.filter((item)=>item.match).length,resumeReadyToday:today.filter((item)=>item.resumeVersion).length,applicationReadyToday:today.filter((item)=>item.application?.status==="READY_FOR_APPLICATION").length,ultraCallsToday:ultra.length,ultraAverageLatency:ultra.length?Math.round(ultra.reduce((sum,item)=>sum+item.latencyMs,0)/ultra.length):0,ultraTasksAvoidedByDeterministicLogic:today.filter((item)=>item.resumeStrategy==="MASTER_RESUME"&&["NONE","LOW"].includes(item.tailoringOpportunity?.estimatedBenefit??"NONE")).length,applicationsSubmittedToday:0,emailsSentToday:0};}
export async function readBrainSnapshot(userId:string):Promise<BrainSnapshot>{const[records,activities,reviews]=await Promise.all([readBrainRecords(userId),readWorkerActivities(userId),readReviewQueue(userId)]);return{records,activities,reviews,metrics:brainMetrics(records)};}
