import { calculatePriority, matchJob, RolevanaOrchestrator, runWorkerPool, type BrainRecord, type WorkerActivity } from "@rolevana/brain";
import { parseEnv } from "@rolevana/config";
import { readLocalJobs, readLocalJobById } from "./job-store";
import { readLocalProfile, readLocalResume } from "./local-store";
import { readBrainRecords, saveBrainRecord, saveWorkerActivities } from "./brain-store";

const assertSafety=()=>{const env=parseEnv(process.env);if(!env.DRY_RUN)throw new Error("PHASE_3A_REQUIRES_DRY_RUN");if(!env.FREE_AI_ONLY||env.MAX_AI_COST_USD!==0)throw new Error("FREE_AI_SAFETY_ASSERTION_FAILED");return env;};
export async function processWithRolevana(userId:string,jobId:string,workerId:number|null=null){const env=assertSafety();const[job,profile,resume]=await Promise.all([readLocalJobById(userId,jobId),readLocalProfile(userId),readLocalResume(userId)]);if(!job||!profile)throw new Error("JOB_OR_PROFILE_NOT_FOUND");const record=new RolevanaOrchestrator({minimumMatchScore:env.MINIMUM_MATCH_SCORE}).process(job,profile,resume,workerId);await saveBrainRecord(userId,record);return record;}
export async function runRolevanaBrain(userId:string,requestedLimit:number){const env=assertSafety();const limit=[1,5,10].includes(requestedLimit)?requestedLimit:1;const[jobs,profile,resume,existing]=await Promise.all([readLocalJobs(userId),readLocalProfile(userId),readLocalResume(userId),readBrainRecords(userId)]);if(!profile)throw new Error("PROFILE_NOT_FOUND");const completed=new Map(existing.map((item)=>[item.jobId,item]));const candidates=jobs.filter((job)=>{const id=job.id??job.descriptionHash;const prior=completed.get(id);return !prior||prior.jobHash!==job.descriptionHash||!["APPLICATION_PREPARED","NEEDS_REVIEW","REJECTED_ROLE","REJECTED_LOCATION","REJECTED_EXPERIENCE"].includes(prior.state);}).map((job)=>{const match=matchJob(job,profile);return{job,priorityScore:calculatePriority(job,match).score};}).sort((left,right)=>right.priorityScore-left.priorityScore).slice(0,limit);
  const activities:WorkerActivity[]=Array.from({length:env.ROLEVANA_WORKER_CONCURRENCY},(_,index)=>({workerId:index+1,jobId:null,jobTitle:null,company:null,state:"IDLE"}));await saveWorkerActivities(userId,activities);const records:BrainRecord[]=[];
  await runWorkerPool(candidates,env.ROLEVANA_WORKER_CONCURRENCY,async(candidate,workerId)=>{activities[workerId-1]={workerId,jobId:candidate.job.id??candidate.job.descriptionHash,jobTitle:candidate.job.title,company:candidate.job.companyName,state:"QUALIFYING"};await saveWorkerActivities(userId,activities);const record=new RolevanaOrchestrator({minimumMatchScore:env.MINIMUM_MATCH_SCORE}).process(candidate.job,profile,resume,workerId);records.push(record);await saveBrainRecord(userId,record);activities[workerId-1]={workerId,jobId:null,jobTitle:null,company:null,state:"IDLE"};await saveWorkerActivities(userId,activities);});return records.sort((left,right)=>right.priorityScore-left.priorityScore);
}
